### PR TITLE
Add support for Flow language server

### PR DESCRIPTION
**Pull request by osener**
Both type hints & company completion appear to work nicely!

### CODE REVIEW

**Comment by osener** [comment]
I'll open a PR for Melpa inclusion as soon as possible, if this is looks good enough to merge. Thanks!

**Comment by vibhavp** [comment]
Why not make lsp-flow a standalone repository? I don't know much about the MELPA build system, so I'm not sure how can you create two packages from the same repository,

**Comment by osener** [comment]
The repository is called `emacs-lsp/lsp-javascript` and TypeScript support has a qualified package name, this made me think the intention was to co-locate lsp clients for these languages (they are two sides of the same coin after all). I believe including Flow support here would make it much easier to find and contribute to it. 

Packaging it for Melpa is easy:

```elisp
(lsp-javascript-typescript
 :fetcher github
 :repo "emacs-lsp/lsp-javascript"
 :files ("lsp-javascript-typescript.el"))

(lsp-javascript-flow
 :fetcher github
 :repo "emacs-lsp/lsp-javascript"
 :files ("lsp-javascript-flow.el"))
```

**Comment by vibhavp** [comment]
I completely forgot this existed, sorry about that.

**Comment by osener** [comment]
@vibhavp No worries, thank you for merging this & for emacs-lsp. It has been working really well for me, much smoother experience than minor modes that interact with Flow's old CLI directly. 

I've submitted a recipe to melpa: https://github.com/melpa/melpa/pull/5284. Once that's in, I want to work on making a out-of-box Flow development environment for Emacs similar to https://github.com/flowtype/ide-flowtype (maybe as a Spacemacs layer?). This will require fine-tuning the lsp client definition and introducing some customization similar to what [lsp-haskell](https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el) does. Can I submit those changes to this module, or would you like to keep it barebones?

**Pull request merged**
